import { Copy } from "lucide-react";
import { useTranslation } from "react-i18next";


export default function FacebookCaption(){
  const { t } = useTranslation('productDetail')


const caption =
`
🎀 Cap

💵 ${t('captionPrice')}: $8.00

🎨 ${t('captionColors')}: ខ្មៅ, ខៀវ

✅ ${t('captionQuality')}

📩 ${t('captionOrderVia')}: សារ!!!
`;



function copyCaption(){

navigator.clipboard.writeText(caption);

}



return (

<div
className="
rounded-[20px]
border
border-[#E7E8E9]
bg-white
p-5
"
>


<h2
className="
font-semibold
"
>
{t('forFacebookPost')}
</h2>



<div
className="
mt-4
rounded-xl
bg-[#F3F4F3]
p-4
whitespace-pre-line
text-sm
"
>

{caption}

</div>



<button
onClick={copyCaption}
className="
mt-4
flex
w-full
items-center
justify-center
gap-2
rounded-xl
bg-[#00351B]
py-3
font-semibold
text-white
"
>

<Copy size={18}/>

{t('copyData')}

</button>



<p
className="
mt-3
text-xs
text-[#666666]
"
>
{t('autoGeneratedText')}
</p>


</div>

);

}