import { useTranslation } from 'react-i18next'
import { Copy } from 'lucide-react'

interface CreateFacebookCaptionProps {
  name: string
  categoryLabel: string
  price: string
}

export default function CreateFacebookCaption({
  name,
  categoryLabel,
  price,
}: CreateFacebookCaptionProps) {
  const { t } = useTranslation('productDetail')

  return (
    <div className="rounded-[20px] border border-[#E7E8E9] bg-white p-5">
      <h2 className="text-sm font-semibold text-[var(--dp-ink)]">
        {t('forFacebookPost') || 'For Facebook post'}
      </h2>
      <div className="mt-4 rounded-[14px] bg-[var(--dp-surface-2)] p-4 text-sm text-[var(--dp-body)]">
        <div className="space-y-2">
          <span className="block">🎀 {name || t('enterProductName') || 'Enter product name'}</span>
          <span className="block">💵 {t('captionPrice') || 'Price'}: {price ? `$${price}` : '—'}</span>
          <span className="block">🏷 {t('category') || 'Category'}: {categoryLabel}</span>
          <span className="block">✅ {t('captionQuality') || 'Full quality'}</span>
          <span className="block">📩 {t('captionOrderVia') || 'Order via'}: message</span>
        </div>
      </div>
      <button
        type="button"
        className="mt-4 inline-flex items-center justify-center gap-2 rounded-full bg-[var(--dp-green-900)] px-4 py-2.5 text-sm font-semibold text-white"
        onClick={() => navigator.clipboard.writeText('🎀 ...')}
      >
        <Copy size={16} />
        {t('copyData') || 'Copy data'}
      </button>
      <p className="mt-3 text-xs text-[var(--dp-muted)]">
        {t('autoGeneratedText') || 'Generated automatically for your Facebook post.'}
      </p>
    </div>
  )
}